// F_Programme FMEN__ par ZeCrusher
// Utilitaire en Mode texte 80x25
// R‚alis‚ le: 13/09/1995
// DŠrniŠre modif: 13/09/95


#ifdef __TINY__
#error < Model TINY > Changement !!! Vous devez passer en MODEL LARGE    [TSK_  (C)]
#endif
#ifdef __SMALL__
#error < Model SMALL > Changement !!! Vous devez passer en MODEL LARGE   [TSK_  (C)]
#endif
#ifdef __MEDIUM__
#error < Model MEDIUM > Changement !!! Vous devez passer en MODEL LARGE  [TSK_  (C)]
#endif
