IF KN=1 THEN AI$="Changement de Nom / Couleur / fichier en cours":GOSUB 2100
IF KN=2 THEN AI$="Sauvegarde,Charge,Effacement,Renomme,Ms-dos,Virus,Quitte ":GOSUB 2100
IF KN=3 THEN AI$="Cherche,Remplace,Recherche Exterieur,Barre et Cadre , Options ":GOSUB 2100
IF KN=4 THEN AI$="M‚moire,Tableau Ascii,Sortie DOS page Ecran,.... ":GOSUB 2100
IF KN=5 THEN AI$="Ex‚cution du fichier dans l'‚diteur,Sauvegarde,Debug":GOSUB 2100
IF KN=6 THEN AI$="Imprimer une partie ou la totalit‚ du fichier en cours":GOSUB 2100
IF KN=7 THEN AI$="Copie le block d‚finie par l'utilisateur":GOSUB 2100