IF J=1 THEN AI$="Change le nom du programme en cour sans l'‚ffacer":GOSUB 2100
IF J=2 THEN AI$="Efface le programme en cours de la memoire de l'‚diteur":GOSUB 2100
IF J=3 THEN AI$="Affiche la table des couleurs en cours / Modification ":GOSUB 2100
IF J=4 THEN AI$="Nom du programme placer dans la celule > 0 <  [Entrer pour le s‚lŠctionner] ":GOSUB 2100
IF J=5 THEN AI$="Nom du programme placer dans la celule > 1 <  [Entrer pour le s‚lŠctionner] ":GOSUB 2100
IF J=6 THEN AI$="Nom du programme placer dans la celule > 2 <  [Entrer pour le s‚lŠctionner] ":GOSUB 2100
