IF J=1 THEN AI$="Permet de sauvegarder votre travail sur le disque ":GOSUB 2100
IF J=3 THEN AI$="Ouvre un fichier sur le disque et le place dans l'‚diteur ":GOSUB 2100
IF J=2 THEN AI$="Permet de sauvegarder votre travail avec un nouveau Nom que celui en cour ":GOSUB 2100
IF J=4 THEN AI$="Assemble deux fichiers dans l'‚diteur":GOSUB 2100
IF J=5 THEN AI$="Supprime un fichier sur disque":GOSUB 2100
IF J=6 THEN AI$="Change le nom et ‚xtention du fichier placer sur le disque ":GOSUB 2100
IF J=7 THEN AI$="Charge le plus rapidement possible le fichier dans l'editeur ":GOSUB 2100
IF J=8 THEN AI$="Acc‚de … MS-DOS en pla‡ant THOLL en m‚moire vive ( ÷ 280 Ko ) ":GOSUB 2100
IF J=9 THEN AI$="Charger / Lancer / Visualiser / Ex‚cuter -> un fichier exterieur ":GOSUB 2100
IF J=10 THEN AI$="Quitte le Programme THOLL et retourne … MS-DOS":GOSUB 2100
