IF J=1 THEN AI$="Permet de fixer un chemin de recherche autre que PATH ":GOSUB 2100
IF J=2 THEN AI$="Explication d'une fonction d'un fichier BATCH avec exemple":GOSUB 2100
IF J=3 THEN AI$="Centrage du texte sÇläctionner ( Ligne infÇrieur a 80 caractäres)":GOSUB 2100
IF J=4 THEN AI$="Centrage d'une seule ligne de moins de 80 caractäres ":GOSUB 2100
IF J=5 THEN AI$="DÇplace le texte sur la marge Gauche de l'Çditeur":GOSUB 2100
IF J=6 THEN AI$="DÇplace une ligne sur la marge gauche de l'Çditeur":GOSUB 2100
